[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chat-gpt-rs = "1.4.0"
colored = "2.0.0"
tokio = "1.28.0"
